### ISSUE TITLE
Release workflow fails on `plan` step

### ISSUE THREAD

**Issue by jdidion** [orhun/automated-rust-releases#5]
First, thanks for putting together your blog post and this repo, it's really helpful.

I've replicated your workflows and setup in my own repo. I created a branch, pushed some commits, then opened a PR. The `cargo dist plan` step fails in the PR's checks because `cargo-dist` can't parse the tag name:

```
Run cargo dist plan --tag=2/merge --output-format=json > dist-manifest.json
analyzing workspace:
  × Couldn't parse the version from the provided announcement tag (2/merge)
  ╰─▶ unexpected character 'm' while parsing major version number
```

I believe this is related to the use of `github.ref_name` for the `--tag` option to `cargo dist`. I found [this GitHub issue](https://github.com/github/docs/issues/15319) which discusses how `ref_name` is different for a PR than in other contexts. There was actually a [PR just last week](https://github.com/github/docs/pull/29712/files) to update the documentation to clarify the difference.

There's a couple other places in that run script where ref_name needs to be changed as well.

LMK if you think this belongs as an issue in `cargo-dist` instead.

The upshot is that I think you want to do something like the following in the `plan` step:

```
if [ "${{ github.event_name }}" == "pull_request" ]; then
  ref_name=${{ github.base_ref }}
else
  ref_name=${{ github.ref_name }}
fi
cargo dist plan --tag=${ref_name} --output-format=json > dist-manifest.json
```

**Comment by orhun** [comment]
Thanks for reporting!

I think it would be best to report this at `cargo-dist`. I'm just utilizing the tools with their default configurations in this repo 🐻

**Comment by jdidion** [comment]
Turns out I was using an old version of `cargo-dist`
